ViewComponents/SearchViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Proje1.Models;
using Proje1.ViewModel;

namespace Proje1.ViewComponents
{
    public class SearchViewComponent : ViewComponent
    {
        private readonly ProjeBirContext _sql;

        public SearchViewComponent(ProjeBirContext sql)
        {
            _sql = sql;
        }
        public IViewComponentResult Invoke ()
        {
            ViewBag.AlisKiraye = new SelectList(_sql.AlisKirayes.ToList(), "AlisKirayeId", "AlisKirayeName");
            ViewBag.Menzil = new SelectList(_sql.Menzils.ToList(), "MenzilId", "MenzilName");
            ViewBag.Seher = new SelectList(_sql.Sehers.ToList(), "SeherId", "SeherName");
            SearchModel s = new SearchModel();
            return View(s);
        }
    }
}

Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
	<link rel="stylesheet" href="/css/StyleSheet.css">
	<title>HOME</title>
</head>

<body>

	<div class="basliq w-100">
		<div class="elaqe text-light d-flex">
			<div class="container w-75 pt-2 px-5">
				<p class="d-inline-block">Dəstək xidməti: (012) 599-08-02; (012) 505-08-02</p>
				<a href="" class="text-light mx-2">RU</a>
				<a href="/Home/Like" class="text-light mx-2"><i class="fa-solid fa-heart"></i> Secilmisler</a>
				<a href="/Admin/Giris" class="text-light mx-2"><i class="fa-solid fa-user"></i> Giris</a>
			</div>
		</div>
		<div class="secim1">
			<div class="container d-flex justify-content-between">
				<nav class="d-flex justify-content-between mx-auto">
					<ul>
						<li class="d-inline-block mx-2">
							<a href="/Home/Index" class="text-light">
								<img src="https://bina.azstatic.com/assets/application/header-tabs/binaaz-logo-107847efc4c9cede987e172b22034c7dc6893bf9bc1a4805b540a53b522031a2.svg">
							</a>
						</li>
						<li class="d-inline-block mx-2"><a href="/Home/AlqiSatqi" class="text-light">Alqi-satqi</a></li>
						<li class="d-inline-block mx-2"><a href="/Home/Kiraye" class="text-light">Kiraye</a></li>
						<li class="d-inline-block mx-2">
							<a href="/Home/Agentlik" class="text-light">Agentlikler</a>
						</li>
						<li class="d-inline-block mx-2">
							<a href="/Home/Kompleks" class="text-light">
								Yasayis
								kompleksleri
							</a>
						</li>
						@if (User.Identity.IsAuthenticated)
						{
							@if (@User.Claims.SingleOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.Name).Value == "Admin")
							{
								<li class="d-inline-block mx-2"><a href="/Admin/Tesdiq" class="text-light">Tesdiq</a></li>
							}
							<li class="d-inline-block mx-2"><a href="/Home/Hesab" class="text-light">@User.Claims.SingleOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.Name).Value</a></li>
							<li class="d-inline-block mx-2"><a href="/Admin/Cixis" class="text-light">Cixis</a></li>
						}
					</ul>
					<a href="/Home/ElanYerlesdir">
						<button class="text-light">
							<i class="fa-solid fa-plus p-1 rounded-circle me-2"></i>Elan
							yerlesdir
						</button>
					</a>
				</nav>
			</div>
		</div>

		@await Component.InvokeAsync("Search")

		@*<div class="secim2">
			<div class="container w-75">
				<form action="" class="w-100 px-5 d-flex justify-content-between">
					<select name="" id="">
						<option value="">Alis</option>
						<option value="">Kiraye</option>
					</select>
					<select name="" id="">
						<option value="">Menzil</option>
						<option value="">Yeni tikili</option>
						<option value="">Kohne tikili</option>
					</select>
					<select name="" id="">
						<option value="">Otaq sayi</option>
						<option value="">1</option>
						<option value="">2</option>
						<option value="">3</option>
					</select>
					<select name="" id="">
						<option value="">Baki</option>
						<option value="">Sumqayit</option>
					</select>
					<select name="" id="">
						<option value="">Etrafli axtaris</option>
					</select>
					<div class="qiymet">
						<input type="text" placeholder="Min">
						<input type="text" placeholder="Max">
					</div>
					<button class="text-light">Axtar</button>
				</form>
			</div>
		</div>*@

	</div>

	@RenderBody()

	<section class="section3 w-100 px-5">
		<div class="container w-75 p-3">
			<div class="elaqe w-100 d-flex justify-content-between pb-2">
				<a href="" class="text-dark">Reklam yerlesdirin</a>
				<div class="div1 d-flex justify-content-between">
					<i class="fa-brands fa-facebook-f"></i>
					<i class="fa-brands fa-instagram"></i>
					<a href="" class="text-dark"><i class="fa-solid fa-envelope"></i> bina@bina.az</a>
					<div class="d-flex justify-content-between">
						<i class="fa-solid fa-phone"></i>
						<div class="ps-2">
							<a href="" class="d-block text-dark">(012) 599-08-02</a>
							<a href="" class="d-block text-dark">(012) 505-08-02</a>
						</div>
					</div>
				</div>
			</div>
			<div class="baki w-100 my-2">
				<h6>Bakinin rayonlari</h6>
				<div class="rayonlar">
					<a href="">Abseron</a>
					<a href="">Bineqedi</a>
					<a href="">Xetai</a>
					<a href="">Xezer</a>
					<a href="">Qaradaq</a>
					<a href="">Nerimanov</a>
					<a href="">Nesimi</a>
					<a href="">Nizami</a>
					<a href="">Pirallahi</a>
					<a href="">Sabuncu</a>
					<a href="">Sebail</a>
					<a href="">Suraxani</a>
					<a href="">Yasamal</a>
				</div>
			</div>
			<div class="azerbaycan">
				<h6>Butun Azerbaycan</h6>
				<div class="yuxari my-3">
					<a href="">Baki</a>
					<a href="">Xirdalan</a>
					<a href="">Sumqayit</a>
					<a href="">Qebele</a>
					<a href="">Quba</a>
					<a href="">Gence</a>
					<a href="">Xacmaz</a>
					<a href="">Ismayilli</a>
					<a href="">Seki</a>
					<a href="">Samaxi</a>
					<a href="">Lenkeran</a>
					<a href="">Qusar</a>
				</div>
				<div class="asagi">
					<a href="">Agcabedi</a>
					<a href="">Agdam</a>
					<a href="">Agdas</a>
					<a href="">Agdere</a>
					<a href="">Agstafa</a>
					<a href="">Agsu</a>
					<a href="">Astara</a>
					<a href="">Balaken</a>
					<a href="">Beyleqan</a>
					<a href="">Berde</a>
					<a href="">Bilesuvar</a>
					<a href="">Cebrayil</a>
					<a href="">Celilabad</a>
					<a href="">Daskesen</a>
					<a href="">Fizuli</a>
					<a href="">Gedebey</a>
					<a href="">Goranboy</a>
					<a href="">Goycay</a>
				</div>
			</div>
		</div>
	</section>

	<footer class="w-100 px-5">
		<div class="container w-75 d-flex justify-content-between text-light">
			<p>
				Saytın Administrasiyası reklam bannerlərinin və yerləşdirilmiş <br> elanların məzmununa görə məsuliyyət
				daşımır.
			</p>
			<p>© 2008-2023 Digital Classifieds MMC. VÖEN: 1405631661</p>
			<a href="" class="text-light">Mobil versiyası</a>
		</div>
	</footer>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
	<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
	<script src="/js/JavaScript.js"></script>
</body>

</html>